# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uniwalluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UniwallUser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UniwallUser'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='content',
            field=models.FileField(upload_to=b'pictures'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UniwallUser'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UniwallUser'),
        ),
    ]
