# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 02:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20151225_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 26, 2, 30, 8, 580767, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
