# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_entry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 12, 26, 20, 4, 4, 722016, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2015, 12, 26, 20, 4, 7, 33121, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
