# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 02:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20151226_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 27, 2, 49, 30, 617876, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
