# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UniwallUser'),
        ),
    ]
